Unify master and ros2 branches (merge ros2 into master)
ros/urdfdom pull request #158
Opened 2021-09-15 18:48 UTC by j-rivero

This PR is a continuation of the work done by @clalancette in #157 (please read all details in the description), after the proposal of modifying the way of merging (merge and not rebase) both branches https://github.com/ros/urdfdom/pull/157#issuecomment-876308696.

I've made a merge in the `master` branch of `ros2` branch in ae6b61d and solve/import some missing pieces in 5a729c1.

Some details I changed on top of Chris work:
* A bit of Cmake trickery to keep old platforms (mainly Bionic) working using old CMake style. See 203a1b2 for TinyXML and 
e577e81 for the lack of components in CMake.
* Add the CI in github actions for the different options of building mentioned by Chris:
   * System (mainly cmake, make) on Bionic and Focal: 4213a41 
   * ROS1 using catkin_make for Melodic 682ddd7
   * ROS2 using colcon for Galactic 557b007 
 
CI can be easily extended to all the existing platforms and with a bit more of effort to Mac and Windows. The option of including more or change ROS1/ROS2 distributions could go into this PR, for new operative system I would prefer to do it in different PRs.

2021-09-16 21:12 UTC, clalancette requested changes
Thanks for taking this over Jose.  Really good work so far on this.  Here's what I think needs to happen for us to complete this:

1. Finish updating the CMakeLists.txt in response to the TODO comments that are in there.
2. The removal of the tests in urdf_unit_test.cpp is unfortunate.  What I really think we should do there is to change `urdf_unit_test.cpp` back to using gtest, and reinstate the tests that were there.
3. Fix the issues I have inline.

Other than that, I did a diff between the master and ros2 branches, and I think you have all of the relevant changes, so this should be pretty close.

2021-09-16 21:12 UTC, clalancette commented on urdf_parser/CMakeLists.txt
> -
I think we should keep the deprecated executable, since we haven't had a full deprecation cycle for it yet.  That is, we should compile the same source file (`urdf_to_graphviz.cpp`) twice; once with the output name of `urdf_to_graphviz`, and once with the output name of `urdf_to_graphiz`.

2021-09-17 16:17 UTC, j-rivero commented on CMakeLists.txt
> +# TODO: check Silvio's comment https://github.com/ros/urdfdom/pull/157/files#r665932087
Following @traversaro comment at https://github.com/ros/urdfdom/pull/157/files#r665932087

I made:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index c7fd37d..adcdbd1 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -67,9 +67,15 @@ if(WIN32 AND NOT CYGWIN)
 else()
   set(CMAKE_CONFIG_INSTALL_DIR ${CMAKE_INSTALL_LIBDIR}/${PROJECT_NAME}/cmake)
 endif()
-# TODO: check Silvio's comment https://github.com/ros/urdfdom/pull/157/files#r665932087
-string(REGEX REPLACE "[^/]+" ".." RELATIVE_PATH_CMAKE_DIR_TO_PREFIX "${CMAKE_CONFIG_INSTALL_DIR}")
-string(REGEX REPLACE "[^/]+" ".." RELATIVE_PATH_LIBDIR_TO_PREFIX "${CMAKE_INSTALL_LIBDIR}")
+
+file(RELATIVE_PATH
+  RELATIVE_PATH_CMAKE_DIR_TO_PREFIX
+  "${CMAKE_CONFIG_INSTALL_DIR}"
+  "${CMAKE_INSTALL_PREFIX}")
+file(RELATIVE_PATH
+  RELATIVE_PATH_LIBDIR_TO_PREFIX
+  "${CMAKE_INSTALL_LIBDIR}"
+  "${CMAKE_INSTALL_PREFIX}")
 
 add_subdirectory(urdf_parser)
```

But RELATIVE_PATH seems to work with absolute paths:
```
-- urdfdom version 1.0.4
CMake Error at CMakeLists.txt:71 (file):
  file RELATIVE_PATH must be passed a full path to the directory:
  lib/urdfdom/cmake


CMake Error at CMakeLists.txt:75 (file):
  file RELATIVE_PATH must be passed a full path to the directory: lib
```

Not sure if I was doing something wrong.

2021-09-17 16:19 UTC, j-rivero commented on CMakeLists.txt
> -
Agree. Maybe is being used by someone. Reverted https://github.com/ros/urdfdom/pull/158/commits/316bc74d4db3201af5f6900ed0d5d6f753ad335d

2021-09-17 16:19 UTC, j-rivero commented on CMakeLists.txt
> +  set(CMAKE_CXX_STANDARD 14)
Sure https://github.com/ros/urdfdom/pull/158/commits/33a19eb3a379259f90be3063c71dfbde6fd0466e

2021-09-17 16:19 UTC, j-rivero commented on urdf_parser/CMakeLists.txt
> -
ack, https://github.com/ros/urdfdom/pull/158/commits/98e773eeaddcfb31daf9924a4f2574ea0ff3b04c

2021-09-17 16:22 UTC, j-rivero commented
> Thanks for taking this over Jose. Really good work so far on this. Here's what I think needs to happen for us to complete this:
> 
>     1. Finish updating the CMakeLists.txt in response to the TODO comments that are in there.

Before doing that, I did a refactor since all libraries were repeating a good bunch of code. https://github.com/ros/urdfdom/pull/158/commits/bab00d9081eba321db0399069b9e53b1dfec8e30

On top of that:
 * @traversaro suggestion for `DEFINE_SYMBOL` https://github.com/ros/urdfdom/pull/158/commits/f070fbaeb4f3c7b69e6267d1f320581d288f6578
 * @sloretz suggestion for `target_compile_features` https://github.com/ros/urdfdom/pull/158/commits/7fa83d884c86e592d0ababc6346657fff3abf305

> 
>     2. The removal of the tests in urdf_unit_test.cpp is unfortunate.  What I really think we should do there is to change `urdf_unit_test.cpp` back to using gtest, and reinstate the tests that were there.

Ouch, my bad. Reverted https://github.com/ros/urdfdom/pull/158/commits/d6d03030d20560477024a454bcdc25152ed5ad92
 
>     3. Fix the issues I have inline.

I think all them are fixed. CI seems happy https://github.com/j-rivero/urdfdom/actions

Thanks Chris for the review.

2021-09-17 17:41 UTC, clalancette requested changes
I've left a few more comments.  This is getting pretty close now.

2021-09-17 17:41 UTC, clalancette commented on urdf_parser/CMakeLists.txt
> +  urdf_to_graphviz
We're forgetting to install `urdf_to_graphiz` here.

2021-09-17 17:41 UTC, clalancette commented on CMakeLists.txt
> +# TODO: check Silvio's comment https://github.com/ros/urdfdom/pull/157/files#r665932087
Personally, I'd remove the TODO and leave this as-is for this PR.  That keeps it the most "compatible" with what we were doing before.  We can always make this fix later on.

2021-09-17 17:41 UTC, clalancette commented on urdf_parser/CMakeLists.txt
> +    target_compile_features(${add_urdfdom_library_LIBNAME} PUBLIC cxx_std_14)
For what it is worth, I'm not a huge fan of this change.  While it may be better from a pure CMake perspective, there are no C++14 features in any of the installed header files and we don't use this idiom anywhere else in ROS 2.  I'd personally put this back to:

```
# Default to C++14
if(NOT CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 14)
endif()
```

But I won't insist on it.

2021-09-17 17:41 UTC, clalancette commented on urdf_parser/CMakeLists.txt
> +    DEFINE_SYMBOL URDFDOM_EXPORTS
I'm OK with making this change, but we need to make sure that this still compiles on Windows in both Release and Debug mode, and that downstream packages can still call it.

2021-09-17 17:53 UTC, sloretz commented on urdf_parser/CMakeLists.txt
> +    target_compile_features(${add_urdfdom_library_LIBNAME} PUBLIC cxx_std_14)
If downstream packges getting compiling with C++14 minimum is undesirable, then switching `PUBLIC` to `PRIVATE` will prevent it from being exported.

> we don't use this idiom anywhere else in ROS 2

rclcpp uses it: https://github.com/ros2/rclcpp/blob/2801553d61c5a30a0327d5cbc8d28bcd74e9703d/rclcpp/CMakeLists.txt#L181 . I expect more packages will switch over time.

2021-09-17 18:22 UTC, clalancette commented on urdf_parser/CMakeLists.txt
> +    target_compile_features(${add_urdfdom_library_LIBNAME} PUBLIC cxx_std_14)
Ah right, I forgot we did that to get the type adapter stuff into rclcpp.

OK, in that case, feel free to ignore this comment @j-rivero .

2021-09-20 16:45 UTC, j-rivero commented on urdf_parser/CMakeLists.txt
> +  urdf_to_graphviz
ouch https://github.com/ros/urdfdom/pull/158/commits/0386d49d4086e5f23a0aa14f9b7ce477ce75432f

2021-09-20 16:47 UTC, j-rivero commented on CMakeLists.txt
> +# TODO: check Silvio's comment https://github.com/ros/urdfdom/pull/157/files#r665932087
reverted. I left it as it was in the original version.

2021-09-20 17:39 UTC, traversaro commented on .github/workflows/ros2.yaml
> +  build_ros1:
I guess it is a typo:
```suggestion
  build_ros2:
```

2021-09-20 17:54 UTC, clalancette approved these changes
I left one nit inline, and it looks like @traversaro did as well.  Other than those two things, this looks good to me, so I'm going to approve.  Once the nits are fixed, we should definitely run CI on this full change in the context of ROS 2.

2021-09-20 17:54 UTC, clalancette commented on urdf_parser/include/urdf_parser/urdf_parser.h
> +#include <urdf_model/utils.h>
Nit: this is duplicated with above.

2021-09-20 18:03 UTC, j-rivero commented on urdf_parser/CMakeLists.txt
> +    DEFINE_SYMBOL URDFDOM_EXPORTS
Umm. I was playing with Windows and indeed found some problems. Lack of M_PI in https://github.com/ros/urdfdom/pull/158/commits/e90a6e309962e36cc5c10a023f503b698a484438, missing API functions https://github.com/ros/urdfdom/pull/158/commits/f5567907fbd8a6d44aa708188de684eddc47b684 and missing a link https://github.com/ros/urdfdom/pull/158/commits/c81dd7d5ea867f5e8412d8853f0c5def79099769.  Long CI test run is ongoing in ROS2 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15434)](https://ci.ros2.org/job/ci_windows/15434/)

2021-09-20 18:18 UTC, j-rivero commented on urdf_parser/include/urdf_parser/urdf_parser.h
> +#include <urdf_model/utils.h>
4dc8cf6

2021-09-21 13:11 UTC, j-rivero commented
A full CI test on ROS2 (only running test on urdfdom):
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=15250)](http://ci.ros2.org/job/ci_linux/15250/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9969)](http://ci.ros2.org/job/ci_linux-aarch64/9969/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12932)](http://ci.ros2.org/job/ci_osx/12932/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15444)](http://ci.ros2.org/job/ci_windows/15444/)

2021-09-21 14:06 UTC, clalancette commented
> A full CI test on ROS2 (only running test on urdfdom):

This is fine for a first pass, but before we merge I'll suggest we run another CI run with `--packages-above urdfdom`, just to make sure everything downstream is happy.  Also we should run Windows Debug as well, as it can be more picky.

2021-09-21 18:54 UTC, j-rivero commented
> This is fine for a first pass, but before we merge I'll suggest we run another CI run with testing `--packages-above urdfdom`, just to make sure everything downstream is happy. Also we should run Windows Debug as well, as it can be more picky.

We have green light on Windows/Debug:
[![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15445)](https://ci.ros2.org/job/ci_windows/15445/)

CI for `--packages-above urdfdom`
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=15254)](http://ci.ros2.org/job/ci_linux/15254/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9973)](http://ci.ros2.org/job/ci_linux-aarch64/9973/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12938)](http://ci.ros2.org/job/ci_osx/12938/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15450)](http://ci.ros2.org/job/ci_windows/15450/)

2021-09-21 20:52 UTC, clalancette approved these changes
CI looks good here, and Windows Debug was happy as well, so this looks good to me.

The failures on macOS are because the vendored version of gtest in urdfdom is way out of date (1.7.0 vs 1.10.0 that we use in ament).  In order to keep the size of this PR down, I discussed with @j-rivero offline about opening a separate PR that just updates gtest to 1.10.0.  I'll suggest we hold off on merging this PR until that one is ready to go; once that one is ready, we can merge this, then quickly merge that one, and keep CI green.

2021-09-24 19:07 UTC, scpeters approved these changes

2021-09-24 19:12 UTC, clalancette commented
OK, I'm going to go ahead and merge this one, then rebase #161 on top to get CI going green.  Thanks @j-rivero for all of the work here!

2021-09-24 19:12 UTC, merged