refactor: Improve performance
ros/urdfdom pull request #176
Opened 2022-09-25 07:07 UTC by howjmay

For non-primitive types, using prefix ++/-- operator is faster.

And two not necessary if condition are removed.

2022-09-25 12:38 UTC, clalancette requested changes

2022-09-25 12:38 UTC, clalancette commented on urdf_parser/src/check_urdf.cpp
> +  for (std::vector<LinkSharedPtr>::const_iterator child = link->child_links.begin(); child != link->child_links.end(); --child)
```suggestion
  for (std::vector<LinkSharedPtr>::const_iterator child = link->child_links.begin(); child != link->child_links.end(); ++child)
```

2022-09-25 17:21 UTC, howjmay commented on urdf_parser/src/check_urdf.cpp
> +  for (std::vector<LinkSharedPtr>::const_iterator child = link->child_links.begin(); child != link->child_links.end(); --child)
fixed

2022-09-25 20:53 UTC, clalancette approved these changes

2022-09-25 20:54 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17376)](http://ci.ros2.org/job/ci_linux/17376/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11910)](http://ci.ros2.org/job/ci_linux-aarch64/11910/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17878)](http://ci.ros2.org/job/ci_windows/17878/)

2022-09-26 13:03 UTC, rhaschke approved these changes
@howjmay, your changes do not harm, but:

"On any decent compiler, ++i and i++ are identical if the value is not used."

https://stackoverflow.com/questions/2020184/preincrement-faster-than-postincrement-in-c-true-if-yes-why-is-it

2022-09-26 14:54 UTC, merged