Switch from TinyXML to TinyXML2 - rebase
ros/urdfdom pull request #178
Opened 2023-01-17 09:41 UTC by SMillerDev

Continues the work in #99 

I know nothing about urdfdom, but with these changes the work in that PR compiles again

2023-01-17 16:28 UTC, clalancette requested changes
In short, we can't do things exactly like this.  There are too many downstream projects that might depend on the TinyXML APIs.

Instead, what we should do is to *add* TinyXML2 APIs alongside the TinyXML ones, and make the TinyXML ones as deprecated.  Once that is done, and has been released, we can then consider removing the TinyXML APIs.

Does that make sense?

2023-01-17 22:26 UTC, SMillerDev commented
How do you feel about leaving it up to the packager. Essentially cmake would decide what to enable

2023-01-18 00:58 UTC, scpeters commented
> How do you feel about leaving it up to the packager. Essentially cmake would decide what to enable

Relevant context here is that homebrew-core would like to remove the `tinyxml` formula. I'm guessing that @clalancette would be open to adding support for tinyxml2 and a cmake option that disables support for tinyxml

2023-01-18 14:24 UTC, SMillerDev commented on urdf_parser/src/world.cpp
> +#endif
How about this solution?

2023-01-18 15:17 UTC, clalancette commented
> Relevant context here is that homebrew-core would like to remove the tinyxml formula. I'm guessing that @clalancette would be open to adding support for tinyxml2 and a cmake option that disables support for tinyxml

Yes, that would be OK with me.  Though I would say that we should have the default be that *both* TinyXML and TinyXML2 APIs are available, with a CMake option that explicitly disables the TinyXML ones.  That is most consistent with how we generally tick-tock APIs.

That said, @scpeters is the maintainer here so I'll defer final approval to his judgement.

2023-02-06 09:16 UTC, scpeters commented on urdf_parser/src/world.cpp
> +#endif
it took me a while to find a moment to write up what I'd like to see but I've updated the cmake and API in https://github.com/ros/urdfdom/commit/a65ae220196640c00be23f9a4eb9ada3b4858926 (branch `scpeters/tinyxml2`) to match what I think it should look like

2023-02-07 17:04 UTC, SMillerDev commented on urdf_parser/src/world.cpp
> +#endif
Okay, let me find a moment to extend that into the rest of the source. I'll tag you when I have the changes.

2023-02-08 19:05 UTC, SMillerDev commented on urdf_parser/src/world.cpp
> +#endif
I think this is it, not sure what to do with `ModelInterfaceSharedPtr  parseURDF(const std::string &xml_string)` though since the signature stays the same

2023-02-08 21:28 UTC, scpeters commented on urdf_parser/src/world.cpp
> +#endif
thanks! I'll take a look

2023-02-14 10:32 UTC, traversaro commented on urdf_parser/include/urdf_parser/urdf_parser.h
> +  URDFDOM_DLLAPI bool parseModelState(ModelState&, tinyxml2::XMLElement*);
Could it make sense to take the occasion and remove these functions that refer to `tinyxml2` symbols from the public interface, to avoid in the future all the problems that we have now in the `tinyxml` --> `tinyxml2` transition?

We could add  `bool exportURDFToString(const ModelInterface &model,, std::string xml_string)`  and `bool exportURDFToFile(const ModelInterface &model,const std::string& path)` to mirror the existing `parseURDF`  and `parseURDFFile` . If downstream users need the `tinyxml2::XMLDocument`, they can always re-parse the string.

2023-02-14 14:51 UTC, SMillerDev commented on urdf_parser/include/urdf_parser/urdf_parser.h
> +  URDFDOM_DLLAPI bool parseModelState(ModelState&, tinyxml2::XMLElement*);
I'd like to suggest the community picks this up since that seems like a decision that needs more knowledge about the tool than I as a mere packager of the tool possess.

2023-02-14 16:08 UTC, traversaro commented on urdf_parser/include/urdf_parser/urdf_parser.h
> +  URDFDOM_DLLAPI bool parseModelState(ModelState&, tinyxml2::XMLElement*);
Sure @SMillerDev . My comment is indeed more directed towards @scpeters and @clalancette .

2023-02-23 15:36 UTC, SMillerDev commented
At least CI seems to like my last changes

2023-02-24 20:42 UTC, scpeters commented on urdf_parser/include/urdf_parser/urdf_parser.h
> +  URDFDOM_DLLAPI bool parseModelState(ModelState&, tinyxml2::XMLElement*);
@traversaro yes, I think we could get rid of the APIs that write to a `tinyxml2::XMLDocument`. We'd still have the `parse*` methods that read from `tinyxml2::Element*` pointers. Do you have any suggestion for those? I guess since it's a raw pointer, we could use forward declarations and remove the include of `tinyxml2.h`?

2023-02-24 22:44 UTC, traversaro commented on urdf_parser/include/urdf_parser/urdf_parser.h
> +  URDFDOM_DLLAPI bool parseModelState(ModelState&, tinyxml2::XMLElement*);
Either fwd declare, or simply keep them only as private functions?

2023-03-20 00:33 UTC, scpeters commented on urdf_parser/include/urdf_parser/urdf_parser.h
> +  URDFDOM_DLLAPI bool parseModelState(ModelState&, tinyxml2::XMLElement*);
@traversaro what do you think of https://github.com/ros/urdfdom/commit/092b57c20bca37d1d81eaa6da6b08a7bebb04662?

2023-03-20 07:33 UTC, traversaro commented on urdf_parser/include/urdf_parser/urdf_parser.h
> +  URDFDOM_DLLAPI bool parseModelState(ModelState&, tinyxml2::XMLElement*);
Definitely better!

2023-03-20 20:07 UTC, clalancette commented on urdf_parser/include/urdf_parser/urdf_parser.h
> +  URDFDOM_DLLAPI bool parseModelState(ModelState&, tinyxml2::XMLElement*);
@scpeters I'm a little confused; it looks like 092b57c isn't on this branch.  Is that meant to be?

2023-03-20 20:37 UTC, scpeters commented on urdf_parser/include/urdf_parser/urdf_parser.h
> +  URDFDOM_DLLAPI bool parseModelState(ModelState&, tinyxml2::XMLElement*);
it's not on the branch at the moment as this PR is from @SMillerDev's branch. I'm just getting some feedback before pushing it

2023-03-30 05:29 UTC, scpeters commented on urdf_parser/include/urdf_parser/urdf_parser.h
> +  URDFDOM_DLLAPI bool parseModelState(ModelState&, tinyxml2::XMLElement*);
@clalancette I just it to this branch

2023-03-30 19:27 UTC, clalancette requested changes
In short, I like the direction here.  I've left a few pieces of feedback of things to fix.

All of that said, I'd prefer if we held off on merging this until after Iron is released (May of this year).  I can forsee some possible packaging problems with this setup, and I want to make sure we aren't introducing them while we are trying to stabilize Iron.

2023-03-30 19:27 UTC, clalancette commented on cmake/FindTinyXML.cmake
> +endif()
Nit: unnecessary change.

2023-03-30 19:27 UTC, clalancette commented on CMakeLists.txt
> +  # bionic has not cmake module, workaround
```suggestion
  # bionic has no cmake module, workaround
```

2023-03-30 19:27 UTC, clalancette commented on CMakeLists.txt
> +    find_package(TinyXML REQUIRED) # bionic has not cmake module
```suggestion
    find_package(TinyXML REQUIRED) # bionic has no cmake module
```

2023-03-30 19:27 UTC, clalancette commented on cmake/FindTinyXML2.cmake
Do we need this file at all?  I think that TinyXML2 typically ships with a valid, working CMake file, so this seems redundant.  But I could be missing something here.

2023-03-30 19:27 UTC, clalancette commented on CMakeLists.txt
> +link_libraries(${TinyXML2_LIBRARIES})
I'm not 100% sure, but I think these are unnecessary given the `target_link_libraries` calls we are doing later.

2023-03-30 19:27 UTC, clalancette commented on urdf_parser/src/joint.cpp
> +using namespace tinyxml2;
This is kind of pedantic, but I'd prefer if we didn't do this and used `tinyxml2::XMLElement` through the below.  It can be a bit tedious, but if you are in the middle of reading that block of code, it is a sure sign you are looking at the TinyXML2 variants of the APIs.

The same comment goes for all files below.

2023-03-30 19:27 UTC, clalancette commented on urdf_parser/src/model.cpp
> +#ifdef HAVE_TINYXML
```suggestion
}

#ifdef HAVE_TINYXML
```

2023-04-04 14:51 UTC, SMillerDev commented on cmake/FindTinyXML.cmake
> +endif()
```suggestion
endif()

```

2023-04-04 14:59 UTC, SMillerDev commented on CMakeLists.txt
> +link_libraries(${TinyXML2_LIBRARIES})
AFAIR I added these because it didn't work without, but I'm willing to comment them out to try.

2023-04-04 15:03 UTC, SMillerDev commented on cmake/FindTinyXML2.cmake
I can see if we can do without it, this was taken from earlier PRs

2023-04-04 17:16 UTC, scpeters commented on cmake/FindTinyXML2.cmake
I'm guessing it was copied from the approach used for TinyXML but may not be necessary for TinyXML2

2023-04-11 12:55 UTC, rserban commented
I suggest marking variables related to tinyxml2 as non-advanced when DISABLE_TINYXML_SUPPORT is set to 'ON'

2023-04-11 19:21 UTC, rserban commented on cmake/FindTinyXML2.cmake
A problem with FindTinyXML2.cmake as provided is that it does not properly deal with multi-config generators. I want to link urdfdom and dependencies to another project and be able to build that in both Release and Debug (Visual Studio on Windows). I was able to do that only by using tinyxml2-config.cmake.

2023-04-18 11:05 UTC, SMillerDev commented on urdf_parser/src/joint.cpp
> +using namespace tinyxml2;
Done

2023-05-25 03:15 UTC, felixf4xu commented
> In short, we can't do things exactly like this. There are too many downstream projects that might depend on the TinyXML APIs.

I don't quite understand this.

If a downstream project depends on TinyXML, they can still use  tinyxml directly, providing linkage to tinyxml is not urdfdom's responsibility.

BTW, if you check the code of `urdf` (https://github.com/ros2/urdf/blob/humble/urdf/CMakeLists.txt#L9), it depends on `tinyxml2` only, never worried about downstream project that needs tinyxml.

2023-05-25 03:22 UTC, felixf4xu commented
In this issue (https://github.com/ros2/ros2/issues/987), `urdfdom` is the only remaining project that still use `tinyxml`, if `urdfrom` upgraded to `tinyxml2`,  `tinyxml` might be remove from rosdsitro completely, I guess.

2023-11-20 18:51 UTC, ros-discourse commented
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/upcoming-api-break-in-urdfdom/34750/1

2023-11-29 15:50 UTC, closed without merging

2023-11-29 20:56 UTC, SMillerDev commented
I'm just happy it's moving really.